name: dev CI

on:
  push:
    branches:
      - dev
    tags:
      - 'beta-[0-9]+.[0-9]+.[0-9]+'
      - 'dev-[0-9]+.[0-9]+.[0-9]+'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 選擇 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest  # 執行單元測試，如果有的話

